name: 🐞 Bug Report
description: Use this form to report a system bug.
title: "[BUG]: Describe the issue"
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug! Please provide as much information as possible.

  - type: input
    id: bug_description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: "Example: Button X doesn't work when clicked..."
    validations:
      required: true

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See the error
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: "Describe the expected behavior here..."
    validations:
      required: true

  - type: input
    id: environment
    attributes:
      label: Environment
      description: Provide details about the environment where the problem occurred.
      placeholder: "Example: macOS 12.6, Chrome 96.0.4664.110, version 1.0.0"
    validations:
      required: true

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
      placeholder: "Include more relevant details."
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: Paste any relevant logs that might help.
      placeholder: "Relevant logs or error messages."
    validations:
      required: false
