blank_issues_enabled: false
contact_links:
  - name: "Report a Bug"
    url: "https://github.com/edudanntas/novalume/issues/new?template=bug_report.yml"
    about: "Use this form to report problems found in the project."
  - name: "Request a Feature"
    url: "https://github.com/edudanntas/novalume/issues/new?template=feature_request.yml"
    about: "Suggest improvements or new ideas for the project."
  - name: "Create a Task"
    url: "https://github.com/edudanntas/novalume/issues/new?template=task.yml"
    about: "Create a specific task for tracking in the project."
