name: 💡 Feature Request
description: Suggest an idea for this project
title: "[FEATURE] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please fill in the fields below with the necessary information.

  - type: textarea
    id: related_problem
    attributes:
      label: Is Your Feature Request Related to a Problem?
      description: "Describe the problem you're experiencing. Ex.: I'm always frustrated when..."
      placeholder: "Explain the problem or need here."
    validations:
      required: true

  - type: textarea
    id: proposed_solution
    attributes:
      label: Describe the Solution You'd Like
      description: What do you want to happen?
      placeholder: "Describe the desired solution."
    validations:
      required: true

  - type: textarea
    id: alternative_solutions
    attributes:
      label: Describe Alternatives You've Considered
      description: Any other solutions you've tried or thought about?
      placeholder: "Explain the alternatives you've considered."
    validations:
      required: false

  - type: checkboxes
    id: acceptance_criteria
    attributes:
      label: Acceptance Criteria
      description: Define the criteria that indicate the success of the feature.
      options:
        - label: Criterion 1
          required: false
        - label: Criterion 2
          required: false
        - label: Criterion 3
          required: false

  - type: textarea
    id: impact_on_existing_services
    attributes:
      label: Impact on Existing Services
      description: How might this feature impact existing services?
      placeholder: "Explain the impact here."
    validations:
      required: false

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Add any other context or relevant information.
      placeholder: "Include more details or images here."
    validations:
      required: false
