services:
  postgres:
    image: postgres:latest
    container_name: novalume_postgres_customer
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: novalume_customers
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: novalumepostgres
    volumes:
      - postgres_data_customer:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  keycloak:
    image: quay.io/keycloak/keycloak:26.2.4
    container_name: novalume-keycloak
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    ports:
      - "9090:8080"
    command:
      - "start-dev"

volumes:
  postgres_data_customer: