services:
  mongodb:
    container_name: mongodb
    image: mongo:latest
    environment:
      - 'MONGO_INITDB_ROOT_USERNAME=admin'
      - 'MONGO_INITDB_ROOT_PASSWORD=verysecret'
      - 'MONGO_INITDB_DATABASE=novalume-catalog-dev'
    ports:
      - '27017:27017'
    volumes:
      - mongodb:/data/db

  minio:
    image: quay.io/minio/minio
    command: server /data --console-address ":9001"
    container_name: minio
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - minio_data:/data
    ports:
      - '9000:9000'
      - '9001:9001'

volumes:
  mongodb:
  minio_data: