spring:
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
    livereload:
      enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/novalume_orders
    username: postgres
    password: novalumepostgres
  jpa:
    hibernate:
      ddl-auto: create-drop
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest


server:
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: always

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

services:
  product-catalog:
    url: http://localhost:8080/api/v1/products

producer:
  topic: order-topic

logging:
  level:
    root: INFO
    br.com.eduardo: DEBUG
    org.springframework.web: DEBUG