apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "novalume-catalog-service.fullname" . }}-config
  labels:
    {{- include "novalume-catalog-service.labels" . | nindent 4 }}
data:
  application.yaml: |
    spring:
      application:
        name: novalume-catalog-service
      profiles:
        active: {{ .Values.applicationConfig.profile }}
      data:
        mongodb:
          auto-index-creation: true
      jackson:
        default-property-inclusion: non_null
        serialization:
          write-dates-as-timestamps: false
      mvc:
        throw-exception-if-no-handler-found: true

    server:
      port: 8080
      shutdown: graceful

    management:
      endpoints:
        web:
          base-path: /actuator
          exposure:
            include: {{ .Values.applicationConfig.actuatorExposure }}
      endpoint:
        health:
          probes:
            enabled: true

    logging:
      level:
        root: {{ .Values.applicationConfig.logLevel }}
        br.com.eduardo: {{ .Values.applicationConfig.logLevel }}